Repository cwruRobotics/rov-23, pull requests merged in 2023-02, with the labels that each got.

#41 made gui a ros node
  surface/gui/gui/run_gui.py
  surface/gui/launch/gui_launch.py
  surface/gui/setup.py
Labels: enhancement

#44 better gui node
  surface/gui/gui/app.py
  surface/gui/gui/modules/module.py
  surface/gui/gui/run_gui.py
  surface/gui/launch/gui_launch.py
  surface/gui/setup.py
  surface/task_selector/task_selector/basic_task_node.py
  surface/task_selector/task_selector/basic_task_timed_node.py
  surface/task_selector/task_selector/example_request_client.py
  surface/task_selector/task_selector/is_morning_node.py
  surface/task_selector/task_selector/task_requestor.py
Labels: enhancement

#48 Typing investigation
  surface/gui/gui/app.py
  surface/gui/gui/event_nodes/client.py
  surface/gui/gui/event_nodes/event_node.py
  surface/gui/gui/event_nodes/publisher.py
  surface/gui/gui/event_nodes/server.py
  surface/gui/gui/event_nodes/subscriber.py
  surface/gui/gui/modules/logger.py
  surface/gui/gui/modules/task_selector.py
  surface/gui/gui/modules/video_area.py
  surface/task_selector/launch/task_scheduler_launch.py
  surface/task_selector/task_selector/basic_task_node.py
  surface/task_selector/task_selector/basic_task_timed_node.py
  surface/task_selector/task_selector/is_morning_node.py
  surface/task_selector/task_selector/manual_control_node.py
  surface/task_selector/task_selector/task_requestor.py
  surface/task_selector/task_selector/tasks.py
Labels: documentation, enhancement

#49 Gui themes
  surface/gui/doc/README.md
  surface/gui/gui/app.py
  surface/gui/gui/modules/task_selector.py
  surface/gui/launch/gui_launch.py
  surface/gui/package.xml
  surface/gui/setup.py
Labels: enhancement

#52 Float linting
  .github/workflows/arduino-lint.yml
Labels: enhancement

#54 Easy build
  .gitignore
  .vscode/easy_all.sh
  .vscode/easy_build.sh
  .vscode/tasks.json
Labels: enhancement

#57 Readme updates
  README.md
  surface/gui/doc/README.md
  surface/task_selector/doc/README.md
  surface/task_selector/doc/images/SelectorNodeGraph.jpg
  surface/task_selector/doc/images/SelectorNodeGraph.png
  surface/task_selector/launch/task_scheduler_launch.py
  surface/task_selector/setup.py
  surface/task_selector/task_selector/task_selector.py
Labels: documentation, refactor
